import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React from 'react';
import { Rings } from 'react-loader-spinner';
import { BeerPageProps } from '../../src/types';

import styles from '../../styles/BeerPage.module.scss';

const BeerPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const [isLoading, setIsLoading] = React.useState<Boolean>(true);
  const [data, setData] = React.useState<BeerPageProps>();

  const fetchItems = async () => {
    const { data } = await axios.get(`https://api.punkapi.com/v2/beers/${id}`);
    setData(data[0]);
    setIsLoading(false);
  };

  React.useEffect(() => {
    if (id) fetchItems();
  }, [id]);

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>{data?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <div className={styles.backBtn}>{'<'}</div>
      </Link>
      {isLoading ? (
        <div className={styles.loading}>
          <Rings color="#c7c7c7" height={120} width={120} />
        </div>
      ) : (
        <div className={styles.body}>
          <div className={styles.imageCon}>
            <img src={data?.image_url} />
          </div>
          <div className={styles.content}>
            <h2 className={styles.name}>{data?.name}</h2>
            <p className={styles.id}>#{data?.id}</p>
            <h3 className={styles.title}>Tagline:</h3>
            <p className={styles.tagline}>{data?.tagline}</p>
            <h3 className={styles.title}>Description:</h3>
            <p className={styles.description}>{data?.description}</p>
            <h3 className={styles.title}>Brewers Tips:</h3>
            <p className={styles.tips}>{data?.brewers_tips}</p>
            <h3 className={styles.title}>ABV:</h3>
            <p className={styles.tips}>{data?.abv}</p>
            <h3 className={styles.title}>Food pairing:</h3>
            <ul>
              {data?.food_pairing.map((item) => (
                <li>{item}</li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
};

export default BeerPage;
