import type { NextPage } from 'next';
import Head from 'next/head';

import debounce from 'lodash.debounce';

import styles from '../styles/Home.module.scss';

// Components
import BearCard from '../src/components/BearCard';
import SearchInput from '../src/components/SearchInput';
import React from 'react';
import axios from 'axios';

const Home: NextPage = () => {
  const [items, setItems] = React.useState([]);
  const [value, setValue] = React.useState<string>('');

  const fetchItems = async (value: string) => {
    console.log(value);
    const { data } = await axios.get(
      `https://api.punkapi.com/v2/beers${value && '?beer_name=' + value}`,
    );

    console.log(data[0]);
    setItems(data);
  };

  const getBears = React.useCallback(
    debounce((str: string) => {
      fetchItems(str);
    }, 300),
    [],
  );

  React.useEffect(() => {
    if (value) getBears(value);
  }, [value]);

  React.useEffect(() => {
    fetchItems(value);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <SearchInput value={value} setValue={setValue} />
      </div>
    </div>
  );
};

export default Home;
